[package]
name = "tw-stairway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitter-v2 = "0.1.7"
dotenvy = "0.15.5"
once_cell = "1.15.0"
maplit = "1.0.2"